user: 'mdfowler'

diag_basic_info:
    compare_obs: false
    create_html: true
    defaults_overlay_file: adf_variable_defaults_cesm.yaml
    obs_data_loc: /glade/campaign/cgd/amp/amwg/ADF_obs
    cam_regrid_loc: /glade/derecho/scratch/${user}/ADF/regrid
    cam_overwrite_regrid: false
    cam_diag_plot_loc: /glade/derecho/scratch/${user}/ADF/plots
    plot_press_levels: [200,850]
    central_longitude: 180
    num_procs: 8
    redo_plot: true

diag_cam_climo:
    hist_str: cam.h0a
    calc_cam_climo: true
    cam_overwrite_climo: false
    cam_case_name: b.e30_alpha06b.B1850C_LTso.ne30_t232_wgx3.132
    case_nickname: '132'
    cam_hist_loc: /glade/derecho/scratch/hannay/archive//b.e30_alpha06b.B1850C_LTso.ne30_t232_wgx3.132/atm/hist
    cam_climo_loc: /glade/derecho/scratch/${user}/ADF/${diag_cam_climo.cam_case_name}/climo
    start_year: 2
    end_year: 44
    cam_ts_done: false
    cam_ts_save: true
    cam_overwrite_ts: false
    cam_ts_loc: /glade/derecho/scratch/${user}/ADF/${diag_cam_climo.cam_case_name}/ts
    tem_hist_str: cam.h4
    cam_tem_loc: /glade/derecho/scratch/${user}/${diag_cam_climo.cam_case_name}/tem/
    overwrite_tem: false

diag_cam_baseline_climo:
    hist_str: cam.h0a
    calc_cam_climo: true
    cam_overwrite_climo: false
    cam_case_name: b.e23_alpha17f.BLT1850.ne30_t232.093
    cam_hist_loc: /glade/campaign/cgd/amp/amwg/ADF_test_cases/${diag_cam_baseline_climo.cam_case_name}
    cam_climo_loc: /glade/derecho/scratch/${user}/ADF/${diag_cam_baseline_climo.cam_case_name}/climo
    start_year: 10
    end_year: 14
    cam_ts_done: false
    cam_ts_save: true
    cam_overwrite_ts: false
    cam_ts_loc: /glade/derecho/scratch/${user}/ADF/${diag_cam_baseline_climo.cam_case_name}/ts
    tem_hist_str: cam.h4
    cam_tem_loc: /glade/derecho/scratch/${user}/${diag_cam_baseline_climo.cam_case_name}/tem/
    overwrite_tem: false

diag_cvdp_info:
    cvdp_run: false

diag_mdtf_info:
    mdtf_run: false

time_averaging_scripts:
    - create_climo_files

regridding_scripts:
    - regrid_and_vert_interp

analysis_scripts:
    - amwg_table
    - ENSO_acrossRuns

plotting_scripts:
    - global_latlon_map
    - enso_comparison_plots

diag_var_list:
    - SWCF
    - LWCF
    - PRECC
    - PRECL
    - PSL
    - Q
    - U
    - T
    - RELHUM
    - TREFHT
    - TS
    - TAUX
    - TAUY
    - FSNT
    - FLNT
    - LANDFRAC
    - O3

    

